<?php
/**
 * @file
 * Hooks and general functions
 */

/**
 * Implements hook_menu().
 */
function bocu_menu() {
  $items['admin/config/content/bocu'] = array(
    'title' => 'BUEditor one click upload',
    'description' => 'Configure module',
    'page callback' => 'bocu_config_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'bocu.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['admin/config/content/bocu/add'] = array(
    'title' => 'Add template',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bocu_form_template'),
    'access arguments' => array('administer site configuration'),
    'file' => 'bocu.inc',
    'type' => MENU_LOCAL_ACTION,
  );
  
  $items['admin/config/content/bocu/edit/%bocu_template'] = array(
    'title' => 'Edit template',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bocu_form_template', 5),
    'access arguments' => array('administer site configuration'),
    'file' => 'bocu.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['admin/config/content/bocu/delete/%bocu_template'] = array(
    'title' => 'Delete template',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bocu_delete_confirm', 5),
    'access arguments' => array('administer site configuration'),
    'file' => 'bocu.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['bocu/upload'] = array(
    'title' => 'Upload file',
    'page callback' => 'bocu_upload',
    'access callback' => TRUE,
    'file' => 'bocu.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}


/**
 * Implements hook_permission().
 */
function bocu_permission() {
  module_load_include('inc', 'bocu');
  
  $templates = bocu_templates();
  $permissions = array();
  
  foreach ($templates as $template) {
    $permissions['upload files use template ' . $template->tid] = array(
      'title' => t('Upload !extensions files', array('!extensions' => $template->mask)),
    );
  }
  
  return $permissions;
}


/**
 * Implements hook_help().
 */
function bocu_help($path, $arg) {
  switch ($path) {
    case 'admin/config/content/bocu':
      return '<p>' . t('To use module, you need to add a new button to some editor with code !code. Read more info in README.txt', array('!code' => '<code>js: E.showFileSelectionDialog();</code>')) . '</p>';
  }
}


/**
 * Implements hook_preprocess_page().
 */
function bocu_preprocess_page(&$vars) {
  global $base_path;
  
  $scripts = drupal_add_js();
  $item = menu_get_item();
  $bueditor_path = drupal_get_path('module', 'bueditor') . '/';
  $bocu_static_path = drupal_get_path('module', 'bocu') . '/static/';
  
  if (isset($scripts[$bueditor_path . 'bueditor.js']) || $item['path'] == 'admin/config/content/bueditor/%') {
    $templates = bocu_templates();
    $allowed_ext = array();
    foreach ($templates as $template) {
      if (user_access('upload files use template ' . $template->tid)) {
        $allowed_ext = array_merge($allowed_ext, explode(',', $template->mask));
      }
    }
    
    drupal_add_js($bocu_static_path . 'uploadify/jquery.uploadify.v2.1.4.min.js');
    drupal_add_js($bocu_static_path . 'uploadify/swfobject.js');
    drupal_add_js($bocu_static_path . 'bocu.js', array('weight' => 1));
    drupal_add_js(array('bocu' => array(
      'phpsessid'  => session_id(),
      'staticPath' => $base_path . $bocu_static_path,
      'sizeLimit'  => file_upload_max_size(),
      'allowedExt' => '*.' . implode(';*.', $allowed_ext) . ';',
    )), 'setting');
    drupal_add_css($bocu_static_path . 'bocu.css');
  }
}


/**
 * Implements hook_form_alter().
 */
function bocu_form_alter(&$form, &$form_state, $form_id) {
  if (variable_get('bocu_delete_unused_files', 1) && isset($form['#submit'])) {
    array_unshift($form['#submit'], 'bocu_change_files_status');
  }
}


/**
 * Custom form submit.
 * Change status uploaded files to "permanent".
 */
function bocu_change_files_status($form, &$form_state) {
  if (isset($_SESSION['bocu']) && isset($_SESSION['bocu'][$form['#form_id']])) {
    foreach ($_SESSION['bocu'][$form['#form_id']] as $field_name => $files) {
      $field_value = _bocu_field_value_by_html_name($form_state, $field_name);
      foreach ($files as $fid => $file_name) {
        if (strpos($field_value, $file_name) !== FALSE) {
          $file = file_load($fid);
          $file->status = FILE_STATUS_PERMANENT;
          file_save($file);
        }
      }
    }
    unset($_SESSION['bocu'][$form['#form_id']]);
  }
}


/**
 * Return template object by tid
 */
function bocu_template_load($tid) {
  return db_select('bocu_templates', 'bc')->fields('bc')->condition('bc.tid', $tid)->execute()->fetch();
}


/**
 * Return all templates
 */
function bocu_templates() {
  return db_select('bocu_templates', 'bc')->fields('bc')->execute()->fetchAllAssoc('tid');
}


/**
 * Return value by input name
 */
function _bocu_field_value_by_html_name($form_state, $field_name) {
  $parts = explode('[', $field_name);
  $value = &$form_state['values'];
  foreach ($parts as $part) {
    $part = rtrim($part, ']');
    $value = &$value[$part];
  }
  return $value;
}
